### ISSUE TITLE
Installation of tiny-cuda-nn Fails Due to ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by KohsukeIde** [weify627/4D-Rotor-Gaussians#3]
### Issue Summary
When trying to install tiny-cuda-nn using the provided command, the installation fails due to a missing torch module.

The installation process fails with the following error message:
```

ERROR: Command errored out with exit status 1:
  command: /user/ide/4dgs/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"/tmp/42435951.1.gpu/pip-req-build-88l0usft/bindings/torch/setup.py"'; __file__='"/tmp/42435951.1.gpu/pip-req-build-88l0usft/bindings/torch/setup.py"';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))' egg_info --egg-base /tmp/42435951.1.gpu/pip-pip-egg-info-8frjukef
      cwd: /tmp/42435951.1.gpu/pip-req-build-88l0usft/bindings/torch
 Complete output (5 lines):
 Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "/tmp/42435951.1.gpu/pip-req-build-88l0usft/bindings/torch/setup.py", line 9, in <module>
     import torch
 ModuleNotFoundError: No module named 'torch'
```

### Fix

The issue was resolved by using a specific version of pip.  using pip 23.0.1 resolved the issue.
`pip install pip==23.0.1`
see [this issue](https://github.com/NVlabs/tiny-cuda-nn/issues/214#issuecomment-1542297669) for other possible solutions.

### Environment Details
	•	Python version: 3.8
	•	CUDA version: 11.8
	•	Operating System: Linux 
	•	pip version: 23.0.1

**Comment by SoftologyPro** [comment]
pip 23.0.1 is not a fix here.
Same No module named torch error.
