### ISSUE TITLE
Install pytorch3d

### ISSUE THREAD

**Issue by ingra14m** [weify627/4D-Rotor-Gaussians#6]
Sometimes I find that pytorch3d cannot be directly installed through `pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu118_pyt200/download.html`.

If you encounter this problem, just first download the `.whl` file through `wget https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu118_pyt200/pytorch3d-0.7.3-cp38-cp38-linux_x86_64.whl`. And then manually install the pytorch3d through `pip install pytorch3d-0.7.3-cp38-cp38-linux_x86_64.whl`.

**Comment by Joaquin-Gajardo** [comment]
thanks @ingra14m! that was helpful to me :)

**Comment by j-nordling** [comment]
This also helped me!
