### ISSUE TITLE
Problems about preprocessing N3V raw video

### ISSUE THREAD

**Issue by grosshill** [weify627/4D-Rotor-Gaussians#8]
Hi, thanks for your excellent work.

I tried to convert the `cut_roasted_beef` raw video to images using the script `n3v2blender.py`，but it seems something wrong with the variable `filenames`.
```
Traceback (most recent call last):
  File "scripts/n3v2blender.py", line 268, in <module>
    filesnames.sort()
NameError: name 'filesnames' is not defined
```
I examined the source code and I found it might be a small mistake:
```
filenames = os.listdir(images_path)
filesnames.sort()
```
So I changed it to `filenames.sort()` and it worked.

**Comment by weify627** [comment]
Thank you for helping spot this error! The code is updated!
